require("lspconfig")
require("usr.lsp.handlers").setup()
require("usr.lsp.lsp-installer")
require("usr.lsp.autocmds")
require("usr.lsp.inlay-hints")
require("usr.lsp.rust-tools")
require("usr.lsp.scala-metals")
